### ISSUE TITLE
huffingtonpost.com doesn't work

### ISSUE THREAD

**Issue by jgerminario** [spectrum-app/spectrum_chrome_app#3]
Spectrum doesn't show up on CNN. This appears to be consistent behavior. No specific error messages found when trying to use it.

**Comment by cssherry** [comment]
Think that might be backend prefix not being stripped. However, not the issue for CNN

**Comment by jgerminario** [comment]
@cssherry I think this might actually not be a bug. See my email for details. I'll leave this open for now but you can deprioritize if neither of us finds it again.

**Comment by jgerminario** [comment]
**Update** CNN.com now works, but huffingtonpost.com doesn't. I'll add other sites here as needed. CC @cssherry

**Comment by cssherry** [comment]
From Email: 

> None of these loaded the Spectrum tray the first time I loaded them up. It looks, for whatever reason, like it always needs a refresh:
> http://www.foxnews.com/politics/2017/02/28/trumps-first-budget-calling-for-54b-increase-in-defense-spending-faces-gop-hurdle.html 
> http://hosted2.ap.org/APDEFAULT/89ae8247abe8493fae24405546e9a1aa/Article_2017-02-27-US--Trump-Budget/id-f6daf76dd8e945b98c6fe103a050dbc2 
> https://www.nytimes.com/2017/02/28/us/politics/trumps-budget-is-aspirational-reality-in-congress-will-change-it.html
> http://www.dailymail.co.uk/news/article-4261832/Officials-Trump-isnt-cutting-Medicare-Social-Security.html
> So I just checked CNN again and it might actually be working fine. Here's an example that's working for me now:
> http://www.cnn.com/2017/02/27/politics/donald-trump-budget-proposal-cuts/index.html. I think I might have thought it was broken because of the same initial-loading issue that we had before.

**Comment by cssherry** [comment]
Believe the huffington post issue was due to the article not being in the database -- I have created an issue for that (https://github.com/spectrum-app/spectrum_backend/issues/22) and fixed it on the backend. Please share a lint from huffington post that has associations and I will check to see that those links work.

The other links not working were due to trying to call publications/mediabias from localstorage before they were available. For some reason, on those pages, the publications/media_biase localstorage items are not present upon first load of page (might be worth investigating, else we'll have a lot of unnecessary calls to our api asking for publications/media_bias). This issue was fixed in commit 0a965e11adb652dd12244b443b91902bb71fafa3

Some of the links not working might also be due to our parsing of hostname. I'm getting rid of the subdomain part of the hostname to prevent this happening (863da39650c222ede7655f4413a1f68937ff6ed4)
