### ISSUE TITLE
Indicate reliability of publication or article (First Use)

### ISSUE THREAD

**Issue by cssherry** [spectrum-app/spectrum_chrome_app#32]
Visual-wise, we could have a note or a hoverable exclamation mark that will show that information upon hover over, link to https://github.com/spectrum-app/spectrum_backend/issues/29

**Comment by geraldgordinier** [comment]
So, since we have this information in the flydown, and we have limited real-estate, I'd rather consider this a problem of "First Use" learning. In other words I don't want a persistant item in the UI for something they just need to learn once (and we already have an access point), BUT I do want to teach them this the first time they use it (and what sites we support).

So! (Don't kill me)... try this on for size:
- After installation, a tooltip that tells users what Spectrum is and how to get to it
- On first use within an article, a couple more tooltips around the UI
- Only shown once per user

![06_first use 1](https://cloud.githubusercontent.com/assets/3990049/24583179/ab10fe18-16f6-11e7-8407-0b6266369180.png)

![07_first use 2](https://cloud.githubusercontent.com/assets/3990049/24583181/b05e7cf6-16f6-11e7-93d8-ba17da0b5024.png)

How much headache is this?

**Comment by cssherry** [comment]
I like the first use tooltip and the open-by-default behavior. I'll try to fit that in to beta version of the add-on.

The "reliability" Indicator is slightly different though -- it would be an indicator of the publication or article's reliability. Say the user was on the Onion -- according to https://mediabiasfactcheck.com/the-onion/ -- we'd want to somehow indicate that the article was "Satire.  Perhaps the most famous satire site of all time."

**Comment by geraldgordinier** [comment]
Hey - you're super right. I moved that stuff over to https://github.com/spectrum-app/spectrum_chrome_app/issues/34 and will try to get you a little visual for the reliability indicator. We may want to push this post-beta because it will likely push away the fox news viewer, I know that conservatives have had some backlash against snopes? Maybe we can discuss tomorrow though

**Comment by jgerminario** [comment]
Yeah this should be done after the 0.1 beta stuff since this adds a lot of product/branding complexity. I think this is the piece that will need the most user testing, so maybe we make a simple (+hardcoded) version of this after 0.1 so we can try it out on some alpha testers. I especially want to validate this with conservatives because this is one of the bigger possible minefields, but it'll also be good to start asking liberals how they feel about the feature and the benefit it offers. It potentially adds a lot of value if we do it well but we have to be careful.

**Comment by jgerminario** [comment]
Closing this per https://github.com/spectrum-app/spectrum_backend/issues/29, added reference to https://spectrumapp.atlassian.net/wiki/display/PROD/Spectrum+Roadmap
